### ISSUE TITLE
ElevenClock stays on top of everything

### ISSUE THREAD

**Issue by Ditendra08** [marticliment/ElevenClock#1115]
Hello, I don't think this is bug, but it's kinda problem for me and maybe there can be fix for this. Problem is that, I use "Lightshot" app to take a screenshots, which is a super light and useful app. However, I noticed that when taking a screenshot, ElevenClock stays above Lightshot and I don't see buttons of Lightshot. When taking a screenshot everything is dimmed, but ElevenClock. Can something be done about it?

**Comment by marticliment** [comment]
Do you have ElevenClock set to show over fullscreen apps?

**Comment by Ditendra08** [comment]
> Do you have ElevenClock set to show over fullscreen apps?

I don't know. Is there a such setting?

**Comment by marticliment** [comment]
Yes, iif you right-click a clock you will be able to open them

**Comment by Ditendra08** [comment]
> Yes, iif you right-click a clock you will be able to open them

I don't see this option (shover over fullscreen apps) in settings.
https://imgur.com/OfgeDTi

**Comment by Ditendra08** [comment]
> You need to click on ElevenClock Settings -> Clock settings

Okay, I'm in there, but I still don't see such option. This is what I have there:

https://i.imgur.com/LoK7XHp.png

**Comment by marticliment** [comment]
Ok, you have the clock to hide when in fullscreen.
Can you please share your log after opening the software you are using?

ElevenClock settings -> Debugging information -> Open log -> Copy log to clipboard

**Comment by Ditendra08** [comment]
> Ok, you have the clock to hide when in fullscreen. Can you please share your log after opening the software you are using?
> 
> ElevenClock settings -> Debugging information -> Open log -> Copy log to clipboard

Yes, but it's not easy, because when I open Lightshot it stays above anything and everything else is dimmed and can't be clicked until I take a screenshot. This is the log after it
[Log.txt](https://github.com/marticliment/ElevenClock/files/10730959/Log.txt)

**Comment by Ditendra08** [comment]
![image](https://user-images.githubusercontent.com/125346218/218698621-e44bd36e-dcc0-4bb2-8313-7b85591aa45d.png)
This is how the problem looks I'm having.

**Comment by marticliment** [comment]
Ok. I will need you to reinstall ElevenClock from the microsoft store, since the updater is failing for you. 
Version 4.0 introduced some new fullscreen detection mechanisms that might help to fix your issue

**Comment by Ditendra08** [comment]
> Ok. I will need you to reinstall ElevenClock from the microsoft store, since the updater is failing for you. Version 4.0 introduced some new fullscreen detection mechanisms that might help to fix your issue

Okay, I just did it. By the way, I at first I downloaded ElevenClock from outside Microsoft store (probably from here). I didn't know it was on Microsoft store.

**Comment by marticliment** [comment]
This microsoft store version (4.0.1) should fix this issue.
If not, can you please share your log again?

**Comment by Ditendra08** [comment]
> This microsoft store version (4.0.1) should fix this issue. If not, can you please share your log again?

Sadly it didn't fix it. Here's new log info:
[Log2.txt](https://github.com/marticliment/ElevenClock/files/10731123/Log2.txt)

**Comment by marticliment** [comment]
Hi Ditendra08,

I'm afraid the software you are using is causing incompatibilites due to the way it has been built, so this issue can not be fixed. 

However, from v4.0.2 (coming soon), ElevenClock will allow you to hide itself during 5 seconds when hovered, an option that could help you to avoid this issue
