### ISSUE TITLE
[BUG] Persist notification icon (broken after Moment 4/ W1123H2 update)

### ISSUE THREAD

**Issue by totallytavi** [marticliment/ElevenClock#1228]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This proposal is a completely new feature. If you want to suggest an improvement or an enhancement, please use [this template](https://github.com/marticliment/ElevenClock/issues/new?assignees=marticliment&labels=enhancement&projects=&template=enhancement-improvement.yml&title=%5BENHANCEMENT%5D+%28Enter+your+description+here%29)

### Describe the new feature

Currently in newer builds of Windows, the notification icon is still displayed, but given a 0. This is causing some issues with display as the two clocsk are overlapping. An option to keep the notification bar would be useful, as it prevents this clash. A screenshot has been placed before to show the issue at hand:
![image](https://github.com/marticliment/ElevenClock/assets/66774833/2b1fa417-eb5b-46ca-a7b8-334840914f1e)

Of course, when I do get an actual notification, everything is fine. It's just when I have no new notifications that it gets messy.
![image](https://github.com/marticliment/ElevenClock/assets/66774833/708ae1fb-5bea-479c-9ab9-f4e0b93e4c6e)

For debugging's sake, I am a Windows Insider and on the Canary tree.

### Describe how this new feature could help users.

In later builds of Windows, if this becomes a finalised feature, it can prevent the issues shown in the screenshots.

**Comment by totallytavi** [comment]
Looks like an update with `winget upgrade` fixed this issue. Will reopen if the issue appears.

**Comment by marticliment** [comment]
This issue was indeed fixed in the latest update

**Comment by totallytavi** [comment]
Issue is back has returned. I have verified I have the latest version `4.3.0`. I have closed and reopened the app to try to fix this. I am no longer on Insiders.
![image](https://github.com/marticliment/ElevenClock/assets/66774833/ada2fa23-3a15-4b76-9ea4-93d7a384ee24)
However, upon a notification being around, it's fixed along with do not disturb.
![image](https://github.com/marticliment/ElevenClock/assets/66774833/d15d4cb3-4ecf-458c-a797-74d5c65620d3)
![image](https://github.com/marticliment/ElevenClock/assets/66774833/9cc54df9-e0b7-4414-af9e-58c8e97ca349)

<details><summary>Log File</summary>
🟢 Using cached lang file
🟡 Using bundled lang file (forced=True)
It took 0.0019989013671875 to load all language files
---------------------------------------------------------------------------------------------------

   ElevenClock's 4.3.0 (v4.3) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "en"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Warning
 🟠: Handled unexpected exception
 🔴: Unhandled unexpected exception
 🟣: Handled expected exception

🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🟢 Clock on the bottom
🟢 Clock on the right
🔵 Clock geometry: PySide6.QtCore.QRect(1720, 1034, 200, 46)
🔵 Full screen rect:  (0, 0, 1920, 1080)
🔵 Using automatic font color
🔵 Font families   : ['Segoe UI Variable Display Semib', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: 9.0
🔵 Loaded date time format: %H:%M:%S \n%d/%m/%Y  (clock 0
🟢 Loaded clocks in 0.38033628463745117
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, DisableNotifications:True
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File ".\settings.py", line 130, in __init__

🔴   File ".\settings.py", line 130, in __init__

🔴 UnboundLocalError: cannot access local variable 'langName' where it is not associated with a value

🔴 UnboundLocalError: cannot access local variable 'langName' where it is not associated with a value

🔴 Note this traceback was caught by reporter and has been added to the log (cannot access local variable 'langName' where it is not associated with a value)
🔵 Language file up-to-date
🔵 Restart loop: 1
🟡 restartClocks function has not been defined yet!
🟡 restartClocks function has not been defined yet!
🟡 restartClocks function has not been defined yet!
🟡 restartClocks function has not been defined yet!
🔵 Starting update check
🔵 Low cpu mode is set to False. DisableNotifications is set to False
🟢 Loaded everything in 1.6290779113769531
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🟢 Clock on the bottom
🟢 Clock on the right
🔵 Clock geometry: PySide6.QtCore.QRect(1720, 1034, 200, 46)
🔵 Full screen rect:  (0, 0, 1920, 1080)
🔵 Using automatic font color
🔵 Font families   : ['Segoe UI Variable Display Semib', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: 9.0
🔵 Loaded date time format: %H:%M:%S \n%d/%m/%Y  (clock 0
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, DisableNotifications:True
🔵 Restart loop: 1
🔵 Version URL: https://versions.marticliment.com/versions/elevenclock.ver
🟢 Updates not found
🔵 Showing tooltip
🔵 Long date string: dd MMMM yyyy
Action: ('win', 'n')
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🟢 Clock on the bottom
🟢 Clock on the right
🔵 Clock geometry: PySide6.QtCore.QRect(1720, 1034, 200, 46)
🔵 Full screen rect:  (0, 0, 1920, 1080)
🔵 Using automatic font color
🔵 Font families   : ['Segoe UI Variable Display Semib', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: 9.0
🔵 Loaded date time format: %H:%M:%S \n%d/%m/%Y  (clock 0
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, DisableNotifications:True
🔵 Restart loop: 1
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🟢 Clock on the bottom
🟢 Clock on the right
🔵 Clock geometry: PySide6.QtCore.QRect(1720, 1034, 200, 46)
🔵 Full screen rect:  (0, 0, 1920, 1080)
🔵 Using automatic font color
🔵 Font families   : ['Segoe UI Variable Display Semib', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: 9.0
🔵 Loaded date time format: %H:%M:%S \n%d/%m/%Y  (clock 0
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, DisableNotifications:True
🔵 Restart loop: 1
🔵 Announcement URL: https://www.marticliment.com/resources/elevenclock.announcement
🔵 Image URL: https://marticliment.com/resources/translate.png
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🟢 Clock on the bottom
🟢 Clock on the right
🔵 Clock geometry: PySide6.QtCore.QRect(1720, 1034, 200, 46)
🔵 Full screen rect:  (0, 0, 1920, 1080)
🔵 Using automatic font color
🔵 Font families   : ['Segoe UI Variable Display Semib', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: 9.0
🔵 Loaded date time format: %H:%M:%S \n%d/%m/%Y  (clock 0
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, DisableNotifications:False
🔵 Restart loop: 1
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🟢 Clock on the bottom
🟢 Clock on the right
🔵 Clock geometry: PySide6.QtCore.QRect(1720, 1034, 200, 46)
🔵 Full screen rect:  (0, 0, 1920, 1080)
🔵 Using automatic font color
🔵 Font families   : ['Segoe UI Variable Display Semib', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: 9.0
🔵 Loaded date time format: %H:%M:%S \n%d/%m/%Y  (clock 0
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, DisableNotifications:True
🔵 Restart loop: 1
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🟢 Clock on the bottom
🟢 Clock on the right
🔵 Clock geometry: PySide6.QtCore.QRect(1720, 1034, 200, 46)
🔵 Full screen rect:  (0, 0, 1920, 1080)
🔵 Using automatic font color
🔵 Font families   : ['Segoe UI Variable Display Semib', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: 9.0
🔵 Restart loop: 1
🔵 Loaded date time format: %H:%M:%S \n%d/%m/%Y  (clock 0
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, DisableNotifications:True
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🟢 Clock on the bottom
🟢 Clock on the right
🔵 Clock geometry: PySide6.QtCore.QRect(1720, 1034, 200, 46)
🔵 Full screen rect:  (0, 0, 1920, 1080)
🔵 Using automatic font color
🔵 Font families   : ['Segoe UI Variable Display Semib', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: 9.0
🔵 Loaded date time format: %H:%M:%S \n%d/%m/%Y  (clock 0
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, DisableNotifications:True
🔵 Restart loop: 1
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🟢 Clock on the bottom
🟢 Clock on the right
🔵 Clock geometry: PySide6.QtCore.QRect(1720, 1034, 200, 46)
🔵 Full screen rect:  (0, 0, 1920, 1080)
🔵 Restart loop: 1
🔵 Using automatic font color
🔵 Font families   : ['Segoe UI Variable Display Semib', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: 9.0
🔵 Loaded date time format: %H:%M:%S \n%d/%m/%Y  (clock 0
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, DisableNotifications:True
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🟢 Clock on the bottom
🟢 Clock on the right
🔵 Clock geometry: PySide6.QtCore.QRect(1720, 1034, 200, 46)
🔵 Full screen rect:  (0, 0, 1920, 1080)
🔵 Using automatic font color
🔵 Font families   : ['Segoe UI Variable Display Semib', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: 9.0
🔵 Loaded date time format: %H:%M:%S \n%d/%m/%Y  (clock 0
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, DisableNotifications:True
🔵 Restart loop: 1
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🟢 Clock on the bottom
🟢 Clock on the right
🔵 Clock geometry: PySide6.QtCore.QRect(1720, 1034, 200, 46)
🔵 Full screen rect:  (0, 0, 1920, 1080)
🔵 Using automatic font color
🔵 Font families   : ['Segoe UI Variable Display Semib', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: 9.0
🔵 Loaded date time format: %H:%M:%S \n%d/%m/%Y  (clock 0
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, DisableNotifications:True
🔵 Restart loop: 1
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🟢 Clock on the bottom
🟢 Clock on the right
🔵 Clock geometry: PySide6.QtCore.QRect(1720, 1034, 200, 46)
🔵 Full screen rect:  (0, 0, 1920, 1080)
🔵 Using automatic font color
🔵 Font families   : ['Segoe UI Variable Display Semib', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: 9.0
🔵 Loaded date time format: %H:%M:%S \n%d/%m/%Y  (clock 0
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, DisableNotifications:True
🔵 Restart loop: 1
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🟢 Clock on the bottom
🟢 Clock on the right
🔵 Clock geometry: PySide6.QtCore.QRect(1720, 1034, 200, 46)
🔵 Full screen rect:  (0, 0, 1920, 1080)
🔵 Using automatic font color
🔵 Font families   : ['Segoe UI Variable Display Semib', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: 9.0
🔵 Loaded date time format: %H:%M:%S \n%d/%m/%Y  (clock 0
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, DisableNotifications:True
🔵 Restart loop: 1
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🟢 Clock on the bottom
🟢 Clock on the right
🔵 Clock geometry: PySide6.QtCore.QRect(1720, 1034, 200, 46)
🔵 Full screen rect:  (0, 0, 1920, 1080)
🔵 Using automatic font color
🔵 Font families   : ['Segoe UI Variable Display Semib', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: 9.0
🔵 Loaded date time format: %H:%M:%S \n%d/%m/%Y  (clock 0
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, DisableNotifications:True
🔵 Restart loop: 1
🔵 Starting update check
🔵 Version URL: https://versions.marticliment.com/versions/elevenclock.ver
🟢 Updates not found
</details>

**Comment by marticliment** [comment]
hello, which windows version are you running?

**Comment by totallytavi** [comment]
Build number is `22621.2361`. I recently installed the Moment 4 update.

**Comment by marticliment** [comment]
You are right, I forgot to change it

**Comment by marticliment** [comment]
Hello guys,

Please update ElevenClock to version 4.3.1 to get this issue fixed.

**Comment by totallytavi** [comment]
Verified the issue is resolved. Closing this!
![image](https://github.com/marticliment/ElevenClock/assets/66774833/232b37ad-3cc6-4783-84a4-21d398603188)
![image](https://github.com/marticliment/ElevenClock/assets/66774833/a79c46eb-b8d5-485f-bc9b-0201eb3e2c10)
![image](https://github.com/marticliment/ElevenClock/assets/66774833/d46f903a-e142-491c-878e-5c5c8fc843fc)

**Comment by OwlBurst** [comment]
I have a similar bug where when I have the fullscreen app on the second monitor open, Windows enables Do not Disturb more, which breaks how ElevenClock overlays over the Windows clock because the Do not Disturb bell icon shows up that gets hidden when I unfullscreen the said app

Happens when Windows has the System -> Notifications -> Notifications -> Show notification bell icon off. DnD bell is showing up anyway

<img width="186" height="116" alt="Image" src="https://github.com/user-attachments/assets/4a6db283-9309-40ab-9576-6850c9bae844" />

No ElevenClock:

<img width="173" height="111" alt="Image" src="https://github.com/user-attachments/assets/6ecdde82-0ffb-42ee-8488-ea449391153c" />

**Comment by marticliment** [comment]
I will check what I can do
